import Head from "next/head"
import Button from "../button"
import styles from '@/styles/Home.module.css'
import { useRouter } from "next/router"

const Navbar = () => {
  const router = useRouter()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.navbar}>
        <h3 className={styles.title}>
          Navbar
        </h3>
        <div>
          <Button onClick={() => router.push('/')} style="flat">
            Home
          </Button>
          <Button onClick={() => router.push('/about')} style="flat">
            About
          </Button>
          <Button onClick={() => router.push('/login')} style="flat">
            Login
          </Button>
        </div>
      </div>
    </>
  )
}

export default Navbar