import Head from "next/head"
import Button from "../button"
import styles from '@/styles/Home.module.css'

const Navbar = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className={styles.navbar}>
        <h3 className={styles.title}>
          Navbar
        </h3>
        <div>
          <Button>
            Home
          </Button>
          <Button>
            Login
          </Button>
          <Button>
            Register
          </Button>
        </div>
      </div>
    </>
  )
}

export default Navbar