import Navbar from "@/components/navbar"
import Head from "next/head"

const Layout = ({ children, metaTitle, metaDescription }) => {
  return (
    <>
      <Head>
        <title>{`Rizal's nextjs project - ${metaTitle}`}</title>
        <meta
          name="description"
          content={metaDescription || "Generated by create next app"}
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      {children}
    </>
  )
}

export default Layout